name: geocheat
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.0
  hooks_riverpod:
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.0
  flutter_svg:
  freezed_annotation: ^2.4.1
  json_annotation:
  flutter_math_fork: ^0.7.0
  easy_localization: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  freezed: ^2.4.5
  json_serializable:
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/translations/

flutter_launcher_icons:
  image_path: assets/logos/app_icon.png
  android: true
  ios: true
  remove_alpha_ios: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/logos/app_icon.png
  web:
    generate: true
    image_path: assets/logos/app_icon.png
    background_color: "#ffffff"
    theme_color: "#ffffff"
  macos:
    generate: true
    image_path: assets/logos/app_icon.png
  windows:
    generate: true
    image_path: assets/logos/app_icon.png
